# -*- coding: utf-8 -*-
"""Eco_News_Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxPqAI2zeKY_-4MrhP0jKrHnUwWDJaM5
"""

!pip install feedparser

import feedparser # This is the library that reads news feeds
from datetime import datetime

# 1. Define the source (This is a major sustainability news feed)
RSS_URL = "https://www.sciencedaily.com/rss/earth_climate/sustainability.xml"

def run_eco_scraper():
    # 2. Fetch the data from the internet
    feed = feedparser.parse(RSS_URL)

    # 3. Create a filename with today's date
    today = datetime.now().strftime("%Y-%m-%d")
    filename = f"Sustainability_Report_{today}.txt"

    # 4. Open a file and write the headlines
    with open(filename, "w") as file:
        file.write(f"--- DAILY SUSTAINABILITY REPORT: {today} ---\n\n")

        for entry in feed.entries[:10]:  # Let's grab the top 10 news items
            file.write(f"TITLE: {entry.title}\n")
            file.write(f"LINK: {entry.link}\n")
            file.write("-" * 30 + "\n")

    print(f"Success! Your report '{filename}' is ready. Check the folder icon on the left.")

# 5. Run the function
run_eco_scraper()